# fly.toml file generated for flask-app on 2024-12-04

app = "api-speechbrain"  # Your app's name

[build]
  dockerfile = "Dockerfile"  # Path to the Dockerfile

[env]
  PORT = "8080"  # Make sure this matches the port your app runs on

[deploy]
  release_command = "python3 manage.py migrate"  # Optional, if you have migrations
